Changes TAB for whitespaces Also adds logos for slock screen on *   .local/bin/chars-arch.txt *   .local/bin/chars-slock.txt

diff --git a/.local/bin/setxtheme b/.local/bin/setxtheme
--- a/.local/bin/setxtheme
+++ b/.local/bin/setxtheme
@@ -3,15 +3,15 @@
 
 # Print message to desktop notification or stdin
 notify () {
-	pgrep dunst 1> /dev/null && dunstify "Colourscheme loaded" "$1" || echo "Loaded the '$1' colourscheme"
+    pgrep dunst 1> /dev/null && dunstify "Colourscheme loaded" "$1" || echo "Loaded the '$1' colourscheme"
 }
 
 themes_dir="$XDG_CONFIG_HOME/xres/themes"
 fname=$(find "$themes_dir" -type f -printf '%f\n' | sort | dmenu -nb '#000000' -nf '#DC122A' -sb '#DC122A' -sf '#000000' -fn 'Ubuntu-11' -p 'Which colourscheme?')
 
 if [ ! -f "$themes_dir/$fname" ]; then
-	echo "Invalid '$fname' theme, doing nothing..."
-	exit 1
+    echo "Invalid '$fname' theme, doing nothing..."
+    exit 1
 fi
 
 cp "$themes_dir/$fname" ~/.config/xresources-term
